### ISSUE TITLE
A least a warning on small mistakes

### ISSUE THREAD

**Issue by schoeberl** [freechipsproject/chisel3#1300] opened 2020-01-17 19:49 UTC
I had a minor typo in the following code. Check how long it takes you to spot it:
```
  def pwm(max: Int, din: UInt) = {
    val cntReg = RegInit(0.U(log2Up(max)))
    cntReg := Mux(cntReg === max.U, 0.U, cntReg + 1.U)
    cntReg >= din
  }
```
This compiles fine, but does not work.
The correct version is:
```
  def pwm(max: Int, din: UInt) = {
    val cntReg = RegInit(0.U(log2Up(max).W))
    cntReg := Mux(cntReg === max.U, 0.U, cntReg + 1.U)
    cntReg >= din
  }
```

How long does it take you to see the difference when given both examples? How long would it take a student learning Chisel to figure out what is wrong? I assume we can address this issue with the strict import not allowing assignments of different sized words.

Cheers,
Martin

**Comment by seldridge** [comment] 2020-01-17 20:02
Unfortunately, there's no consensus on how to handle this as bit extraction from a literal is widely used. Trying to handle this with the proposed strict option might work as that could introduce restricted semantics.

Closing as duplicate of discussion on #1184. See also closed issue #871

**Closed by seldridge** 2020-01-17 20:02 UTC
